var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/mypage/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__413996ed._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_025b2a8d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17c77370._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d8001078._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__6515bb8b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_mypage_page_actions_9f0e3979.js")
R.m(25493)
module.exports=R.m(25493).exports
